name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - master  # La branche principale qui déclenchera le déploiement
  pull_request:
    branches:
      - master  # Lintera les Pull Requests vers master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Assurez-vous d'utiliser la bonne version de Node.js

    - name: Install dependencies
      run: npm install

    - name: Build Angular app
      run: npm run build -- --output-path=dist --base-href="/<ton-repo>/"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
