name: Deploy to GitHub Pages  # Le nom du workflow

on:  # Événements qui déclenchent le workflow
  push:
    branches:
      - main  # Sur la branche 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Spécifie le système d'exploitation

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build the Angular app
      run: npm run build -- --output-path=dist --base-href="/REPO_NAME/"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
